version: '3.9'

services:
  user-db:
    image: postgres:15
    container_name: user-db

    environment:
      POSTGRES_DB: users
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

    ports:
      - "15434:5432"

    volumes:
      - user-db-data:/var/lib/postgresql/data # save DB data between reloading

    networks:
      - booking-net

  property-db:
    image: postgres:15
    container_name: property-db
    environment:
      POSTGRES_DB: properties
      POSTGRES_USER: property
      POSTGRES_PASSWORD: password
    ports:
      - "15435:5432"
    volumes:
      - property-db-data:/var/lib/postgresql/data # save DB data between reloading

    networks:
      - booking-net

volumes:
  user-db-data:
  property-db-data:

networks:
  booking-net:
    driver: bridge